"""Added is_lost to statistics

Revision ID: 5765cfc5366a
Revises: d22ecba86cc4
Create Date: 2023-03-06 16:55:01.012851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5765cfc5366a'
down_revision = 'd22ecba86cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column(
        'is_lost', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'is_lost')
    # ### end Alembic commands ###
