"""Added is_winner field to statistics table

Revision ID: 6b954ac73bc9
Revises: c93bf151d299
Create Date: 2023-03-10 17:18:00.967379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b954ac73bc9'
down_revision = 'c93bf151d299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('is_winner', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'is_winner')
    # ### end Alembic commands ###
