"""Rename fisrt_name to first_name in users

Revision ID: 36ef0cb492ff
Revises: 2ad63ae3f10e
Create Date: 2023-03-23 13:43:21.286311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ef0cb492ff'
down_revision = '2ad63ae3f10e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.drop_column('users', 'fisrt_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fisrt_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
