"""Added first_name and last_name to users

Revision ID: 2ad63ae3f10e
Revises: 6b954ac73bc9
Create Date: 2023-03-23 13:34:01.283040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad63ae3f10e'
down_revision = '6b954ac73bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fisrt_name', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'fisrt_name')
    # ### end Alembic commands ###
