"""change first_name and last_name to nullable true

Revision ID: 66221b312dd1
Revises: 36ef0cb492ff
Create Date: 2023-03-23 13:53:09.015967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66221b312dd1'
down_revision = '36ef0cb492ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
